"""
Clean.py

Purpose:
- Read data/search_volume.csv generated by Aggregate.py
- Apply minimal cleaning only
- Remove only:
  1. number-only terms
  2. obvious UI/navigation/policy terms
  3. reddit username/system terms
- Keep long phrases intact
- Do NOT split words
- Do NOT merge similar phrases yet
- Do NOT judge product relevance yet

Input:
    data/search_volume.csv

Output:
    data/clean_search_volume.csv
    data/removed_search_volume.csv

Run:
    python Clean.py
"""

from __future__ import annotations

import csv
import re
from pathlib import Path
from typing import Optional


DATA_DIR = Path("data")
INPUT_CSV = DATA_DIR / "search_volume.csv"
CLEAN_OUTPUT_CSV = DATA_DIR / "clean_search_volume.csv"
REMOVED_OUTPUT_CSV = DATA_DIR / "removed_search_volume.csv"


UI_NAV_POLICY_TERMS = {
    # account / auth
    "sign in",
    "sign up",
    "log in",
    "login",
    "logout",
    "create account",
    "my account",
    "my wishlist",
    "wish list",
    "cart",
    "shopping bag",
    "track orders",
    "order status",

    # policy / legal
    "privacy policy",
    "user agreement",
    "terms of use",
    "terms & conditions",
    "terms and conditions",
    "terms & policies",
    "cookie policy",
    "accessibility",
    "legal information",
    "email collection policy",
    "return policy",
    "membership policy",
    "influencer terms & conditions",
    "your privacy choices",
    "all rights reserved",

    # navigation / menu / generic site actions
    "home",
    "search",
    "open navigation",
    "close",
    "close popup",
    "open menu",
    "open settings menu",
    "expand navigation",
    "collapse navigation",
    "expand user menu",
    "skip to main content",
    "main text shortcuts",
    "previous",
    "next",
    "view more",
    "view all moderators",
    "learn more",
    "get started",
    "download app",
    "contact us",
    "customer service",
    "faqs",
    "faq",
    "language",
    "currency",
    "cancel",
    "facebook",
    "instagram",

    # reddit UI/system
    "wiki",
    "moderators",
    "moderator list hidden.",
    "message mods",
    "community bookmarks",
    "community information",
    "community actions",
    "reddit rules",
    "reddit resources",
    "about reddit",
    "best of reddit",
    "reddit pro beta",
    "developer platform",
    "installed apps",
    "go to reddit home",
    "create post",
    "stickied post",
    "locked post",
    "archived post",
    "open user actions",
    "filter by flair",
    "flair filter (hide)",
    "evasion guard",
    "bot bouncer",
    "admin tattler",
    "entity highlight panel",
    "media poster",
    "media error",
    "public",
    "primary",
    "compact",
    "hot",
    "rising",
    "feed",
    "press",
    "advertise",
    "careers",
    "announcement",
    "resources",

    # TikTok/marketing UI
    "see analytics",
    "view on tiktok",
    "connect via tiktok one",
    "tiktok for business",
    "top ads",
    "top ads dashboard",
    "trends overview",
    "products & services",
    "creative strategies",
    "supported languages",
    "approved for business use",
    "api",
    "automation",
}


UI_NAV_POLICY_CONTAINS = [
    # auth / account
    "sign up for reddit",
    "log in to reddit",
    "open settings menu",
    "open menu open navigation",
    "expand user menu",

    # policy / legal
    "privacy policy",
    "user agreement",
    "all rights reserved",
    "terms & conditions",
    "terms and conditions",
    "terms & policies",

    # reddit boilerplate
    "reddit, inc.",
    "reddit rules",
    "reddit resources",
    "moderator list hidden",
    "message the mod team",
    "community bookmarks",
    "community information",
    "anyone can view, post, and comment",
    "best open sort options",
    "valid title tags",
    "related subs",
    "referral threads",
    "research threads",
    "routine megathreads",
    "holy grail threads",
    "no/low buy threads",
    "how to post",
    "how to patch test",
    "the sca routine",
    "search the sub",
    "flair filter",

    # obvious ads/promoted system strings
    "promoted",
    "advertisement:",
    "media error",
    "media poster",

    # site menus
    "customer service",
    "track orders",
    "download app",
    "shipping location",
    "shopping preferences",
    "membership benefits",
]


REDDIT_USERNAME_PATTERN = re.compile(r"^u/[a-z0-9_\-]+(?:\s*[•-].*)?$", re.IGNORECASE)
REDDIT_SUB_PATTERN = re.compile(r"^r/[a-z0-9_\-]+(?:\s+rules)?$", re.IGNORECASE)
NUMBER_ONLY_PATTERN = re.compile(r"^[\d\s.,:/+\-]+$")
HTML_ENTITY_PATTERN = re.compile(r"^&[a-z]+;$", re.IGNORECASE)


def normalize_for_check(value: Optional[str]) -> str:
    if not value:
        return ""
    value = value.lower()
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def is_number_only(term: str) -> bool:
    term = normalize_for_check(term)
    if not term:
        return True
    return bool(NUMBER_ONLY_PATTERN.fullmatch(term))


def is_ui_nav_policy(term: str) -> bool:
    term = normalize_for_check(term)

    if term in UI_NAV_POLICY_TERMS:
        return True

    if HTML_ENTITY_PATTERN.fullmatch(term):
        return True

    for fragment in UI_NAV_POLICY_CONTAINS:
        if fragment in term:
            return True

    return False


def is_reddit_system(term: str) -> bool:
    term = normalize_for_check(term)

    if REDDIT_USERNAME_PATTERN.fullmatch(term):
        return True

    if REDDIT_SUB_PATTERN.fullmatch(term):
        return True

    if term.startswith("author: u/"):
        return True

    return False


def removal_reason(term: str) -> Optional[str]:
    if is_number_only(term):
        return "number_only"

    if is_reddit_system(term):
        return "reddit_username_or_system"

    if is_ui_nav_policy(term):
        return "ui_navigation_policy"

    return None


def read_csv(path: Path) -> list[dict]:
    if not path.exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    with path.open("r", newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def write_csv(rows: list[dict], path: Path, fieldnames: list[str]) -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = read_csv(INPUT_CSV)

    clean_rows: list[dict] = []
    removed_rows: list[dict] = []

    for row in rows:
        term = row.get("search_term", "")
        reason = removal_reason(term)

        if reason:
            removed = dict(row)
            removed["removed_reason"] = reason
            removed_rows.append(removed)
        else:
            clean_rows.append(row)

    original_fieldnames = list(rows[0].keys()) if rows else [
        "search_term",
        "search_volume",
        "source_count",
        "sources",
        "example_raw_phrase",
    ]

    write_csv(clean_rows, CLEAN_OUTPUT_CSV, original_fieldnames)
    write_csv(removed_rows, REMOVED_OUTPUT_CSV, original_fieldnames + ["removed_reason"])

    print(f"input rows: {len(rows)}")
    print(f"clean rows: {len(clean_rows)} -> {CLEAN_OUTPUT_CSV}")
    print(f"removed rows: {len(removed_rows)} -> {REMOVED_OUTPUT_CSV}")
    print()
    print("TOP 50 CLEAN TERMS")

    for row in clean_rows[:50]:
        print(
            f"{row.get('search_term', '')} | volume={row.get('search_volume', '')} | "
            f"sources={row.get('source_count', '')}"
        )


if __name__ == "__main__":
    main()
